version: '2.1'

services:

  mysql_db:
    image: mysql:8.0.23
    container_name: mysql_db
    environment:
        - MYSQL_DATABASE=warehouse_db
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_USER=warehouse
        - MYSQL_ROOT_HOST= %
        - MYSQL_ALLOW_EMPTY_PASSWORD=  1
    ports:
        - '3306'
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-psecret" ]
    networks:
        warehouse-network:
            aliases:
                - mysql_db
  rabbitmq:
      image: rabbitmq:3.6.1-management
      container_name: rabbitmq
      user: root
      environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=secret
      ports:
          - "5672:5672"
          - "15672:15672"
      networks:
          warehouse-network:
              aliases:
                  - rabbitmq
  warehouse:
      image: warehouse:1.0
      environment:
          - RABBITMQ_HOST=rabbitmq
          - RABBITMQ_USER=guest
          - RABBITMQ_PASSWORD=secret
          - DATABASE_URL=jdbc:mysql://mysql_db:3306/warehouse_db?serverTimezone=UTC
          - DATABASE_USER=warehouse
          - DATABASE_PASSWORD=secret
          - JAVA_OPTS= -server -Xms2048m -Xmx2048m -XX:+UseG1GC -Xlog:gc*
      ports:
          - "8080:8080"
      depends_on:
          mysql_db:
              condition: service_healthy
      networks:
          warehouse-network:
              aliases:
                  - warehouse

networks:
    warehouse-network:
        driver: bridge
